FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests 

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/SpringBootMVCFirstApp-3-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java","-jar","app.war"]

#docker run -d -p 8081:8080 springboot-app:1.0
